### ISSUE TITLE
config for goo to never be dead

### ISSUE THREAD

**Issue by 800020h** [Direwolf20-MC/JustDireThings#208]
### Describe the feature you'd like to have added

currently `goo_can_die = false` means goo won't die after the initial feeding
but it's still dead when you place it

what I want is goo to also be alive when you place it
this could be with another config option, or changing the behaviour of `goo_can_die`

### Additional information

the current behaviour of these examples is the same
although the second one might be worse for performance (not tested but the info after tick sprinting seemed to suggest it)
```toml
#1
goo_can_die = false
goo_death_chance = 0.1
```
```toml
#2
goo_can_die = true
goo_death_chance = 0.0
```
changing the behaviour of `goo_can_die` would mean example 2 is the only way to have goo only require an initial feeding

technically the behaviour I want can be achieved with a datapack by changing the recipes and loot tables to put the block state data on the item
